@localBasePath=http://localhost:7071
@afBasePath=https://myserverlessreqbin-func.azurewebsites.net
@basePath={{afBasePath}}

GET {{basePath}}/12345?a=1&b=2
x-my-header:1234567890
DISGUISED-HOST:xyz

###
POST {{basePath}}/12345
x-my-header:1234567890
DISGUISED-HOST:xyz
X-SITE-DEPLOYMENT-ID:xyz

<xml>Hello from VS CODE!</xml>


###
PUT {{basePath}}/12345?a=1&b=2
x-my-header:1234567890

<xml>Hello from VS CODE!</xml>


###
PATCH {{basePath}}/12345?a=1&b=2
x-my-header:1234567890

<xml>Hello from VS CODE!</xml>


###
HEAD {{basePath}}/12345?a=1&b=2

###
OPTIONS {{basePath}}/12345?a=1&b=2

###
DELETE {{basePath}}/12345?a=1&b=2

###
TRACE {{basePath}}/12345?a=1&b=2

###
GET {{basePath}}/history/12345

###
DELETE {{basePath}}/history/12345