@localBasePath=http://localhost:7071
@afBasePath=https://testingdurable-func.azurewebsites.net
@basePath={{afBasePath}}
@binId=123456789

GET {{basePath}}/{{binId}}?a=1&b=2
x-my-header:1234567890
DISGUISED-HOST:xyz

###
POST {{basePath}}/{{binId}}
x-my-header:1234567890
DISGUISED-HOST:xyz
X-SITE-DEPLOYMENT-ID:xyz

{
  "question": "Why are people affraid of computers?",
  "answer": "They byte!"
}


###
PUT {{basePath}}/{{binId}}?a=1&b=2
x-my-header:1234567890

{
  "question": "Why do Java programmers have to wear glasses?",
  "answer": "Because they don't C#"
}


###
PATCH {{basePath}}/{{binId}}?a=1&b=2
x-my-header:1234567890

{
  "question": "What's another name for a computer virus",
  "answer": "A terminal inllness"
}


###
HEAD {{basePath}}/{{binId}}?a=1&b=2

###
OPTIONS {{basePath}}/{{binId}}?a=1&b=2

###
DELETE {{basePath}}/{{binId}}?a=1&b=2

###
TRACE {{basePath}}/{{binId}}?a=1&b=2

###
GET {{basePath}}/history/{{binId}}

###
DELETE {{basePath}}/history/{{binId}}